server:
  port: 9001

spring:
  application:
    name: cloud-payment-service
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    instance-id: cloud-payment-service9001
    prefer-ip-address: true
  client:
    register-with-eureka: true # 是否向注册中心注册自己
    fetch-registry: true # 是否需要检索服务
    service-url:
      defaultZone: http://eureka-register1:7001/eureka/,http://eureka-register2:7002/eureka/,http://eureka-register3:7003/eureka/

feign:
  httpclient:
    connection-timeout: 10000 # 连接超时，默认2秒
  hystrix:
    enabled: true # 服务降级

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

logging:
  level:
    com.xzy.feign: debug