server:
  port: 7001

eureka:
  instance:
    hostname: localhost # Eureka 服务端的实例名称
  client:
    register-with-eureka: false # 是否向注册中心注册自己
    fetch-registry: false # 是否需要检索服务
    service-url: # 与 Eureka Service 对外提供服务的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/